sisimai:
  domain: 'libsisimai.org'
  author: 'azumakuniyuki'
  version: '5.5.0'
  v4final: '4.25.17'
  blogurl: 'https://blog.libsisimai.org/post/717456764036104192/sisimai-42516'
  release: 
    en: 'Friday, 5th December 2025'
    ja: '令和7年12月05日(金)'
  spec:
    modules: 60
    reasons: 36
    bhratio: 59
    license: 'The BSD 2-Clause License'
  workson:
    perl: ["5.26.0", "5.42.0"]
    ruby: ["2.5.9", "3.4.7"]
    jruby: ["9.2", "9.4"]
    golang: ["1.24.0", "1.25.4"]
  diff:
    tests:
      perl: "330,000"
      ruby: "410,000"
      golang: "253,000"
    loc:
      perl: "9,900"
      ruby: "9,900"
      golang: "9,100"
    parse1k:
      perl: 1.37
      ruby: 1.95
      golang: 0.37
    timesfaster:
      perl: 3.0
      ruby: 2.6
      golang: 12.2
    fasterthan4:
      perl: 1.00
      ruby: 1.00
      golang: 4.40
  pronounced: '/ɕi.ɕi.ma.i/'
  repository:
    project: 'https://github.com/sisimai'
    perl: 'https://github.com/sisimai/p5-sisimai'
    ruby: 'https://github.com/sisimai/rb-sisimai'
    golang: 'https://github.com/sisimai/go-sisimai'
  distribution:
    perl: 'https://metacpan.org/pod/Sisimai'
    ruby: 'https://rubygems.org/gems/sisimai'
    golang: 'https://pkg.go.dev/libsisimai.org/sisimai/v5'
  socialmedia:
    weblog: 'https://blog.libsisimai.org/'
    twitter: 'https://twitter.com/libsisimai'
    tumblr: 'https://libsisimai.tumblr.com/'
    facebook: 'https://www.facebook.com/libsisimai/'
html:
  ss: "<span class = 'ss'>Sisimai</span>"
  bh: "<span class = 'bh'>bounce<strong>Hammer</strong></span>"
  cr: "<span class = 'ss'>Cubicroot</span>"
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

